### ISSUE TITLE
Support io.js

### ISSUE THREAD

**Issue by callumacrae** [tkellen/node-liftoff#30]
Not sure how this would work. Are there any plans to support io.js?

**Comment by tkellen** [comment]
Liftoff should work fine with io.js.  There are some small issues with a companion library that can be leveraged to get automatic re-spawning for flags like `--harmony`, though (node-v8flags).

**Comment by callumacrae** [comment]
Cool, I wasn't sure how it worked. So if it's called using io.js, it'll run stuff using io.js?

The harmony flag is default in io.js, so that one in particular wouldn't be an issue.
