### ISSUE TITLE
deprecate requires option

### ISSUE THREAD

**Issue by silkentrance** [tkellen/node-liftoff#37]
With rechoir in place, the requires option is no longer required.

**Comment by tkellen** [comment]
The requires option could be used for more than pre-loading js-variant interpreters.

**Comment by silkentrance** [comment]
With rechoir in place, the requires option should no longer be used to load pre-load js-variant compilers/transpilers.

**Comment by phated** [comment]
Rechoir isn't in place, as noted in https://github.com/tkellen/node-rechoir/issues/17

Allowing people to require anything will allow them to pre-load transpilers if they choose.  There is no way to restrict that.

**Comment by silkentrance** [comment]
@phated Why isn't rechoir in place? This seems to be a issue to me, liftoff not being able to reuse the node-interpret registry nor node-rechoir, altogether reimplementing the same behaviour.

**Comment by phated** [comment]
@silkentrance what are you talking about?  Liftoff already uses interpret.  rechoir added new functionality for legacy module support which hasn't been backported to liftoff.  As mentioned in the linked issue, having specific functionality in rechoir for a __very__ liftoff-specific feature is undesirable.

**Comment by silkentrance** [comment]
@phated having synchronized my clone with the current master, there is no dependency towards node-interpret whatsoever. I do not know what you are talking about.

**Comment by phated** [comment]
@silkentrance I think you need to investigate how all of these libraries work together.  You can see how they are used at https://github.com/gulpjs/gulp/blob/master/bin/gulp.js#L21-L26

**Comment by silkentrance** [comment]
@phated you are not abstracting away the whole problem. The extensions option is actually obsolete, or, rather not so obsolete as @tkellen put it, as there are file extensions that are specific to a given tool but which will map to an existing extension that in turn can be mapped to a compiler/transpiler/interpreter instead.

You are making this API depending on the (limited) requirements of gulp instead of making it universal as it was your original intent.

**Comment by phated** [comment]
@silkentrance those tools give their own objects as  `extension -> transpiler` objects and don't use interpret.  You are conflating too many things and are actually trying to make liftoff less flexible.  In no way should liftoff have a hard dependency on interpret.  The only way it will have a dependency on interpret is if we want to use it as a default for extensions (which we probably won't).

**Comment by silkentrance** [comment]
@phated Heck, how difficult can it be, having node-interpret and node-rechoir in place, why would one to reimplement the existing behaviour instead of build on top of it, layer wise...
And in no way I would liftoff to be less flexible, as it is already inflexible as per your provided example, which limits the configuration files to just the available js dialects extensions registered with node-interpret?

**Comment by phated** [comment]
Dude, you are seriously confused.  I can't continue this discussion if you don't understand how the code works.

**Comment by silkentrance** [comment]
@phated

There is no discussion here, my point is correct and yours is ultimately wrong.

**Comment by tkellen** [comment]
Every single invocation of every single tool that uses Liftoff does not need the complexity of your extremely narrow use case. You *can* have what you want right now: fork + npm link = done. Once you've stabilized your in-development language, you can add it to interpret and it'll be published in a matter of hours.

**Comment by silkentrance** [comment]
@tkellen this is not about me, it is about everyone that wants to implement a new dialect or alias an existing extension to another, different extension, for example multigruntfile.multigrunt or something like that.
Something which the current implementation will not support.
And the complexity is near to zero when using appropriate file filters.

**Comment by tkellen** [comment]
Find me 10 people with this problem and I'll re-consider adding this feature.  As it is you can get support for this in a liftoff cli with `tool --require mylang --configfile myconfig.whatever`

**Comment by silkentrance** [comment]
Yes, you are right, however, having --require mylang --configfile myconfig.whatever being obsoleted, what a great gain would that be for the user?

Perhaps the rather simple changes I will propose in my PR will make you think otherwise and help to improve on the reuse of node-rechoir.

**Comment by tkellen** [comment]
`--require` is not going to be obsoleted.

**Comment by silkentrance** [comment]
it will be blatantly ignored instead :grinning: and leaving it to rechoir to figure things out?

**Comment by tkellen** [comment]
The use case for `--require` in liftoff is orthogonal to the problem being
solved by rechoir.

**Comment by silkentrance** [comment]
Actually --require becomes obsolete once rechoir is being used by liftoff. And I do not see any use case other than what I proposed in my now prematurely closed PR over at node-rechoir which would enable users to add arbitrary aliases for existing jsVariants a/o extensions...
