### ISSUE TITLE
options.extensions obsolete?

### ISSUE THREAD

**Issue by silkentrance** [tkellen/node-liftoff#38]
With rechoir in place, the extensions option might no longer be needed.

**Comment by tkellen** [comment]
Not so, the extensions option specifies which extensions are valid for config files.  There are implementations in the wild that use extensions which are not listed (nor should be) in interpret.

**Comment by silkentrance** [comment]
@tkellen As such, the extensions option is rather difficult in that one cannot assume a valid compiler/transpiler from the extension alone. Shouldn't this be more of a map of want - exist, e.g.

```
extensions : {'.foobar' : '.json'}
```

or the likes?
